---
- name: Install Wordpress 
  hosts: "localhost"
  become: true
  roles:
    - { role:  /etc/ansible/roles/bertvv.httpd }
    - { role:  roles/bertvv.mariadb }
    - { role:  roles/ansible-role-wordpress-master }


